[package]
name = "risp"
version = "0.1.0"
authors = ["shadw3002 <702189255@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peekmore = "1.0.0"